language: elm

before_install: "npm install -g parcel-bundler@1.12"

before_deploy: "parcel build index.html --public-url /welsh-whacker/"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master